services:
  - type: web
    name: noleftovers-backend
    env: python
    buildCommand: pip install -r src/requirements.txt
    startCommand: cd src && python App.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 